### ISSUE TITLE
Menu takes several seconds to open on Firefox

### ISSUE THREAD

**Issue by soniCaH** [codebushi/gatsby-starter-forty#14]
Hey, when going to the site preview (https://gatsby-forty.surge.sh) or running the project locally, it takes a few seconds to open the menu from the header.
Same goes for closing it.

I only could test it on Safari as a second browser, and here the menu opens almost instantly.
Any idea what could be causing this behaviour?

![Screen Recording 2020-01-24 at 22 17 21 mov](https://user-images.githubusercontent.com/789034/73105580-b6085680-3ef9-11ea-8ad1-23d5daedd462.gif)

**Comment by soniCaH** [comment]
For anyone interested, the performance is caused by one single line of CSS:

```
@include vendor('filter', 'blur(0.5em)');
```

Performance of CSS filter blurs (especially in combination with transforms) seems to be very poor.

**Comment by ChangoMan** [comment]
Thanks for finding that @soniCaH I try to find an alternative or just remove that CSS.

**Comment by ChangoMan** [comment]
Should be fixed now, I removed that CSS
