### ISSUE TITLE
How to use a function from Grand child of parent 

### ISSUE THREAD

**Issue by fa16mscs0004** [codebushi/gatsby-starter-forty#6]
I want to call handleToggleVideoModel from Grand child Banner.js file
handleToggleVideoModel  exist in layout/index.js
code is here
    `class Template extends React.Component {

    constructor(props) {
    super(props)
    this.state = {
        isMenuVisible: false,
        isVideoModelVisible: false,
        loading: 'is-loading'
    }
    this.handleToggleVideoModel = this.handleToggleVideoModel.bind(this)

    }

    handleToggleVideoModel() {
    alert('test handleToggleVideoModel ');
    console.log('layout');
    this.setState({
        isVideoModelVisible: !this.state.isVideoModelVisible
    })
    }
    render() {
    const { children } = this.props
    return (

       {children()}

    )
    }
    }
    Template.propTypes = {
    children: React.PropTypes.func,
    handleToggleVideoModel: React.PropTypes.func
    }

    export default Template`

Then as we know childern will contain pages/index.js 
which is in my case look like this

    `class HomeIndex extends React.Component {

    constructor(props) {
    super(props);
    }
    render() {
    return (
            <Banner onToggleVideoModel= {this.props.handleToggleVideoModel}/>
        )
    }

    }`

and finally Banner.js file which is place in Component/Banner.js

    `const Banner = (props) => (
    <section id="banner" className="major">
    <li><a href="javascript:void(0);" className="button next" onClick= 
    {props.onToggleVideoModel}>Watch video</a></li>
    </section>
     )
     export default Banner`

here i want to toggle handleToggleVideoModel  from Banner comonent
layout/index.js (parent)
pages/index.js (Child)
Components/Banner.js (Grand child)

**Comment by ChangoMan** [comment]
You might want to try the Context API https://reactjs.org/docs/context.html. You could also try to map over this.props.children and pass in props like this: https://stackoverflow.com/questions/50293335/how-to-pass-props-through-this-props-children-not-this-props-children
