### ISSUE TITLE
Gatsby - Got error when compiling the images

### ISSUE THREAD

**Issue by bythelabo** [codebushi/gatsby-starter-forty#9]
Dear Chango 

I'm really like your theme - clear and efficient. thx for it 

I raise a issue about image compilation - could you please help me to resolve it ? 
https://github.com/theofromthelabo/thelabo/issues/1

Thank you - I'm discovering Gatsby ;-) 

Have a good day

**Comment by bythelabo** [comment]
Dear Chango - 

Following up - have you received my message as above ? 

thanks and have good day !

**Comment by ChangoMan** [comment]
Seems like this was resolved
